### ISSUE TITLE
SpringBoot分支GoodsKillRpcServiceApplication启动报错

### ISSUE THREAD

**Issue by MeetMax** [techa03/goodsKill#34]
错误信息如下：

```java
12:04:06.838 [main] ERROR org.seckill.util.common.util.AESUtil - 
javax.crypto.IllegalBlockSizeException: Input length must be multiple of 16 when decrypting with padded cipher
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:936)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:847)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
	at javax.crypto.Cipher.doFinal(Cipher.java:2165)
	at org.seckill.util.common.util.AESUtil.aesDecode(AESUtil.java:100)
	at org.seckill.util.common.util.EncryptPropertyPlaceholderConfigurer.convertProperty(EncryptPropertyPlaceholderConfigurer.java:23)
	at org.springframework.beans.factory.config.PropertyResourceConfigurer.convertProperties(PropertyResourceConfigurer.java:106)
	at org.springframework.beans.factory.config.PropertyResourceConfigurer.postProcessBeanFactory(PropertyResourceConfigurer.java:83)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:286)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:166)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)
	at org.seckill.service.GoodsKillRpcServiceApplication.main(GoodsKillRpcServiceApplication.java:24)

```

**Comment by techa03** [comment]
可以检查一下connections.properties这个配置文件，master.password和slave.password是不是都配置过了，可以使用AESUtil工具类进行数据库密码加解密

**Comment by MeetMax** [comment]
> 可以检查一下connections.properties这个配置文件，master.password和slave.password是不是都配置过了，可以使用AESUtil工具类进行数据库密码加解密

必须要使用主从吗？有没有单个数据库使用过的方法？

**Comment by MeetMax** [comment]
```json
//数据库驱动以及连接信息
master.driver=com.mysql.cj.jdbc.Driver
master.url=jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
master.username=root
//数据库密码（已加密，本项目AESUtil工具类可以加密）
master.password=+tkfyiKcqLiFlgt7GSnxtw==

slave.driver=com.mysql.cj.jdbc.Driver
slave.url=jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
slave.username=root
slave.password=+tkfyiKcqLiFlgt7GSnxtw==
```
这是我local的配置信息，连的是同一个数据库，另外由于我本地MySQL为5.7，我把 mysql-connector-java 配置的版本改成了5.1.46，如下：
```xml
<dependency>
          <groupId>mysql</groupId>
         <artifactId>mysql-connector-java</artifactId>
         <version>5.1.46</version>
        <scope>runtime</scope>
</dependency>
```

**Comment by techa03** [comment]
> ```json
> ```json
> //数据库驱动以及连接信息
> master.driver=com.mysql.cj.jdbc.Driver
> master.url=jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
> master.username=root
> //数据库密码（已加密，本项目AESUtil工具类可以加密）
> master.password=+tkfyiKcqLiFlgt7GSnxtw==
> 
> slave.driver=com.mysql.cj.jdbc.Driver
> slave.url=jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
> slave.username=root
> slave.password=+tkfyiKcqLiFlgt7GSnxtw==
> ```
> 
> 
> 这是我local的配置信息，连的是同一个数据库，另外由于我本地MySQL为5.7，我把 mysql-connector-java 配置的版本改成了5.1.46，如下：
> ```
> <dependency>
>           <groupId>mysql</groupId>
>          <artifactId>mysql-connector-java</artifactId>
>          <version>5.1.46</version>
>         <scope>runtime</scope>
> </dependency>
> ```
> ```

单数据库的配成一样的就可以

**Comment by techa03** [comment]
> ```json
> ```json
> //数据库驱动以及连接信息
> master.driver=com.mysql.cj.jdbc.Driver
> master.url=jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
> master.username=root
> //数据库密码（已加密，本项目AESUtil工具类可以加密）
> master.password=+tkfyiKcqLiFlgt7GSnxtw==
> 
> slave.driver=com.mysql.cj.jdbc.Driver
> slave.url=jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
> slave.username=root
> slave.password=+tkfyiKcqLiFlgt7GSnxtw==
> ```
> 
> 
> 这是我local的配置信息，连的是同一个数据库，另外由于我本地MySQL为5.7，我把 mysql-connector-java 配置的版本改成了5.1.46，如下：
> ```
> <dependency>
>           <groupId>mysql</groupId>
>          <artifactId>mysql-connector-java</artifactId>
>          <version>5.1.46</version>
>         <scope>runtime</scope>
> </dependency>
> ```
> ```

我用的MySQL8.0，最好保持一致吧，另外8.0跟5.1.46驱动类名是不一样的
